# DO NOT COMMIT THIS FILE (local only).

[auth.users.admin]
name = "Admin"
role = "admin"
exporters = ["*"]
password_hash = "pbkdf2_sha256$200000$GFy4lGIwf8mBwak6LkxDKg==$eDtcsDZ/Ykz93SZO2wq20LydGk8ciRjEtnpNbNev8Go="

[auth.users.mavuno]
name = "Mavuno User"
role = "exporter"
exporters = ["Mavuno"]
password_hash = "pbkdf2_sha256$200000$c14QxhpntVvBdbN5lNoYyw==$fgsPuHk0NFTdUz2bJ+rZWcPONqOtw47PZ+TpZ3A58Bk="

[auth.users.ktl]
name = "KTL User"
role = "exporter"
exporters = ["KTL"]
password_hash = "pbkdf2_sha256$200000$rql72NTA64QGmThjj6YYrg==$BsIx1xXZyL8QV2C22JEpYu5/UTNe2qsQZKOO8LfGJ/Y="

[auth.users.fresh]
name = "Fresh Produce User"
role = "exporter"
exporters = ["The Fresh Produce company"]
password_hash = "pbkdf2_sha256$200000$IcRE8UmJk6apC620B4vXtQ==$do+qjB05OVMUDjKOnyMkk26eAJzDJSbC0Dm+MJ7Wlr8="
